default:
	$(MAKE) -C ./Tiles
	$(MAKE) -C ./Board
	$(MAKE) -C ./BoardManager
	$(MAKE) -C ./BoardRules

clean:
	$(MAKE) -C ./Tiles -f Makefile clean
	$(MAKE) -C ./Board -f Makefile clean
	$(MAKE) -C ./BoardManager -f Makefile clean
	$(MAKE) -C ./BoardRules -f Makefile clean
