default:
	$(MAKE) -C ./Tiles
	$(MAKE) -C ./Board
	$(MAKE) -C ./BoardManager

clean:
	$(MAKE) -C ./Tiles -f Makefile clean
	$(MAKE) -C ./Board -f Makefile clean
	$(MAKE) -C ./BoardManager -f Makefile clean
